version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RAILS_ENV: development
    ports:
      - '3001:3000'
    env_file: .env
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:password@postgres:5433/lti_rooms}
      RAILS_ENV: development
    volumes:
      - .:/usr/src/app
      - bundle-volume:/usr/src/bundle
    links:
      - postgres

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5433:5432"
    command: -p 5433

volumes:
  bundle-volume:
