development:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'async' %>

test:
  adapter: async

production:
  adapter: <%= ENV['CABLE_ADAPTER'] || 'async' %>
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: bbb-app-rooms_production
